#include<stdio.h>
#include<sys/types.h>
#include<unistd.h>
#include<wait.h>
#include<signal.h>
#include<pthread.h>
#include<stdlib.h>
#include<time.h>
#include<string.h>
#include<ctype.h>
#include<sys/time.h>
#include<semaphore.h>
#include<math.h>